### ISSUE TITLE
Expose Multiple Properties

### ISSUE THREAD

**Issue by avdaredevil** [Max00355/Feather#2]
Nice Framework, but you need a few things exposed before it's production ready:
- [x] Route Types [POST, GET, PATCH, etc]
- [x] Client_Secret
- [ ] Maybe add hooks for UDP, WebSockets

**Comment by Max00355** [comment]
@avdaredevil Thanks for the suggestions! I just pushed the change that allows for designating route types.

Commit: https://github.com/Max00355/Feather/commit/c4c4450ca069187983f4699b371e332aaa832e33

Updated Readme: https://github.com/Max00355/Feather/README.md

**Comment by Max00355** [comment]
Also, what do you suggest for the UDP WebSockets?

**Comment by Max00355** [comment]
Client secret and AES encrypted sessions have been added. I am going to close this issue. If possible, an elaboration on how you imagine the websockets working would be great. 

Thanks!

**Comment by avdaredevil** [comment]
Sure, I'd say look into how [`Flask-Sockets`](https://gist.github.com/drewww/1402238) handles it.

There might be a goldmine [here](https://docs.python.org/2/library/socketserver.html) as well.

Let me know if you'd need more input.
